stages:
  - test

test:
  image: node:latest
  stage: test
  when: manual
  before_script:
    # install dependencies
    - npm ci
  script:
    # start the server in the background
    - npm start &
    # run Cypress tests
    - npm run e2e
